[build-system]
requires      = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"


[project]
name = "embedstore"
version = "0.0.6"
description = "Retrieving the most relevant context for your LLMs"
readme = "README.md"
license = { file = "LICENSE" }


dependencies = [
   'requests >= 2'
]
requires-python = ">=3.8.1,<4.0"